twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Spring
    - Microservices
    - Kafka
    - Elasticsearch
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
